### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by sangorrin** [williamhaley/custom-debian-iso-creator#1]
Hi William!

I have noticed that you didn't write any License (and Copyright) information for your awesome scripts.
It would be great if you did :)

Thanks,
Daniel

**Comment by williamhaley** [comment]
See https://github.com/williamhaley/custom-debian-iso-creator/commit/f8ee057d7819e5b7c204d156bcbf9476054c0aee

Thanks!

**Comment by sangorrin** [comment]
Thanks a lot!
